project_id = "decision-under-uncertainty"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[functions.generate-judgment-article]
verify_jwt = false

[functions.publish-next-article]
verify_jwt = false
