begin;

with batch as (
  select * from jsonb_to_recordset($articles$
  [
    {
      "ordinal":2,
      "slug":"sunk-cost-next-decision",
      "title":"이미 쓴 돈은 다음 결정을 지시할 권리가 없다",
      "subtitle":"손실을 인정하지 않으려는 마음과 미래 가치를 분리하는 법",
      "excerpt":"수수료와 시간, 옵션 프리미엄을 이미 지불했다는 이유로 나쁜 선택을 연장할 때가 있습니다. 매몰비용을 미래의 증거와 분리하는 훈련입니다.",
      "category":"행동경제학",
      "tags":["매몰비용","추가투입","옵션","철수규칙"],
      "reading_minutes":7,
      "difficulty":"입문",
      "hero_kicker":"판단 훈련 02 · 매몰비용",
      "content_blocks":[
        {"kind":"paragraph","text":"만기가 가까운 옵션이 큰 손실을 기록하고 있습니다. 처음 지불한 프리미엄이 아까워 추가 계약을 사면 평균단가가 낮아진다는 생각이 듭니다. 그러나 이미 지불해 되돌릴 수 없는 비용은 오늘의 추가 매수가 좋은지 알려주지 않습니다."},
        {"kind":"heading","text":"과거의 비용이 미래의 표처럼 보일 때"},
        {"kind":"paragraph","text":"매몰비용 효과는 돈·시간·노력을 이미 투입했다는 사실 때문에 활동을 계속하려는 경향입니다. 사람은 중단을 낭비의 인정처럼 느끼기 쉽고, 계속하면 과거의 선택을 정당화할 수 있다고 기대합니다."},
        {"kind":"paragraph","text":"하지만 다음 결정의 비교 대상은 ‘지금 멈추기’와 ‘지금부터 더 투입하기’입니다. 최초 비용을 되찾을 가능성이 아니라 추가 비용 이후의 결과 분포, 남은 시간, 대안의 기회비용을 비교해야 합니다."},
        {"kind":"callout","title":"독립된 새 결정으로 바꾸기","text":"이 포지션을 오늘 처음 발견했고 과거 지출이 0원이라면, 현재 가격에 같은 추가 투입을 하겠습니까? 아니오라면 과거 비용이 판단에 끼어든 것입니다."},
        {"kind":"heading","text":"계속하는 것이 합리적인 경우"},
        {"kind":"paragraph","text":"중단이 항상 정답은 아닙니다. 새 정보로 성공확률이 높아졌거나, 철수비용이 크거나, 추가 투입의 기대가치가 대안보다 높다면 계속할 수 있습니다. 핵심은 ‘이미 많이 썼다’가 아니라 ‘지금부터의 순편익이 크다’는 근거입니다."},
        {"kind":"list","items":["회수 불가능한 과거 비용을 따로 적는다","지금부터 드는 추가 비용과 최악의 손실을 적는다","같은 자원으로 가능한 최선의 대안을 적는다","계속 조건과 중단 조건을 숫자로 정한다"]},
        {"kind":"heading","text":"낭비를 줄이는 진짜 방법"},
        {"kind":"paragraph","text":"나쁜 계획을 연장하면 과거의 낭비가 사라지는 것이 아니라 미래 비용이 더해집니다. 합리성은 과거의 나를 무죄로 만드는 일이 아니라, 현재의 내가 다음 손실을 제한하는 일입니다."}
      ],
      "thought_experiment":{"title":"공짜로 받은 동일한 포지션","prompt":"현재 보유 포지션과 손익 구조가 완전히 같지만 진입비용은 다른 사람이 냈다고 가정합니다. 그래도 추가 매수하시겠습니까?","choices":["추가한다","그대로 유지한다","축소하거나 종료한다"],"reflection":"선택이 달라졌다면 어떤 과거 비용이 기준점으로 작동했는지 적어보세요."},
      "practice":{"title":"매몰비용 분리표","minutes":7,"steps":["최근 포기하기 어려웠던 거래나 구매를 고른다","이미 회수 불가능한 비용을 한 칸에 적는다","앞으로의 비용·편익만 새 칸에 적는다","대안 한 가지와 비교한다","중단 조건을 한 문장으로 확정한다"],"rule_template":"이미 쓴 ___원은 제외하고, 지금부터의 ___와 ___만 비교한다."},
      "source_notes":[{"title":"The Psychology of Sunk Cost","authors":"Hal R. Arkes, Catherine Blumer","year":1985,"url":"https://doi.org/10.1016/0749-5978(85)90049-4","note":"이미 투입한 돈·시간·노력이 활동 지속을 높이는 매몰비용 효과를 현장 및 설문 연구로 보여준다."},{"title":"Prospect Theory: An Analysis of Decision under Risk","authors":"Daniel Kahneman, Amos Tversky","year":1979,"url":"https://doi.org/10.2307/1914185","note":"손실 영역의 위험추구와 기준점 의존적 평가를 설명하는 토대를 제공한다."}]
    },
    {
      "ordinal":3,
      "slug":"overconfidence-trading-frequency",
      "title":"확신이 커질수록 주문 버튼에서 한 걸음 멀어져야 한다",
      "subtitle":"예측 정확도와 거래 횟수를 분리하는 과잉확신 점검법",
      "excerpt":"정보를 많이 봤다는 느낌은 예측력이 높아졌다는 증거가 아닙니다. 확신, 정확도, 거래비용을 따로 측정하는 기록법을 연습합니다.",
      "category":"행동재무학",
      "tags":["과잉확신","과잉거래","예측","수수료"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 훈련 03 · 과잉확신",
      "content_blocks":[
        {"kind":"paragraph","text":"뉴스, 차트, 커뮤니티 의견을 충분히 확인한 날에는 거래하지 않는 것이 더 어렵습니다. 정보량이 늘수록 ‘무언가 해야 한다’는 감각이 커지지만, 정보량과 예측 정확도는 같은 변수가 아닙니다."},
        {"kind":"heading","text":"확신은 측정값이 아니라 느낌일 수 있다"},
        {"kind":"paragraph","text":"과잉확신은 자신의 정보 정확도나 통제력을 실제보다 높게 평가하는 현상입니다. 투자에서는 작은 차이를 확실한 우위로 해석하고 거래 빈도와 포지션 크기를 늘리는 통로가 됩니다."},
        {"kind":"paragraph","text":"Barber와 Odean의 계좌자료 연구는 더 활발한 거래와 낮은 순성과가 함께 나타날 수 있음을 보여줍니다. 이 결과가 모든 잦은 거래가 나쁘다는 뜻은 아니지만, 수수료·스프레드·세금이라는 확정 비용을 이길 만큼 우위가 있는지 묻게 합니다."},
        {"kind":"callout","title":"확신도보다 적중률","text":"매 주문 전에 상승·하락·횡보 확률과 확신도를 적고, 20회 뒤 실제 적중률과 비교하세요. 기억이 아니라 기록으로 보정해야 합니다."},
        {"kind":"heading","text":"전문성과 과잉확신을 구별하기"},
        {"kind":"paragraph","text":"전문가는 근거뿐 아니라 오차범위와 실패 조건을 말할 수 있습니다. 반대로 과잉확신은 반증 조건이 흐리고, 성공은 실력으로 실패는 외부 탓으로 분류하는 경향을 보입니다."},
        {"kind":"list","items":["주장의 반대 증거를 한 개 찾는다","예측 확률을 50·60·70%처럼 수치화한다","비용 차감 후 필요한 최소 우위를 계산한다","거래하지 않기 선택도 기록한다"]},
        {"kind":"heading","text":"좋은 무행동도 결정이다"},
        {"kind":"paragraph","text":"시장은 매일 열리지만 모든 날이 의사결정 기회는 아닙니다. 기준을 통과하지 못한 거래를 건너뛰는 것은 소극성이 아니라, 확신과 우위를 구분한 능동적 선택입니다."}
      ],
      "thought_experiment":{"title":"두 분석가의 차이","prompt":"A는 90% 확신으로 한 방향을 말하지만 기록이 없습니다. B는 62% 확률과 실패 조건, 과거 적중률을 제시합니다. 누구의 포지션 크기를 더 신뢰하시겠습니까?","choices":["A","B","둘 다 거래하지 않는다"],"reflection":"당신이 신뢰한 것은 자신감의 표현인지 검증 가능한 기록인지 구분해보세요."},
      "practice":{"title":"20회 예측 장부 시작","minutes":6,"steps":["다음 거래의 세 가지 결과 확률을 적는다","가장 중요한 근거와 반증 조건을 각각 한 줄 적는다","총비용을 예상손익에서 차감한다","결과 후 예측과 실제를 비교한다"],"rule_template":"확신도가 아니라 기록된 적중률과 비용 차감 후 우위가 ___ 이상일 때만 실행한다."},
      "source_notes":[{"title":"Boys Will Be Boys: Gender, Overconfidence, and Common Stock Investment","authors":"Brad M. Barber, Terrance Odean","year":2001,"url":"https://doi.org/10.1162/003355301556400","note":"개인투자자 계좌자료에서 과잉확신, 거래 빈도, 순성과의 관계를 분석한다."},{"title":"Trading Is Hazardous to Your Wealth","authors":"Brad M. Barber, Terrance Odean","year":2000,"url":"https://doi.org/10.1111/0022-1082.00226","note":"거래가 가장 활발한 가구의 비용 차감 후 성과를 계좌자료로 검토한다."}]
    },
    {
      "ordinal":4,
      "slug":"anchor-price-independence",
      "title":"목표가격을 보기 전에 내 숫자를 먼저 만들어라",
      "subtitle":"앵커가 분석의 출발점을 점령하지 못하게 하는 순서 설계",
      "excerpt":"첫 가격과 전문가 목표치는 이후 추정을 끌어당깁니다. 외부 숫자를 보기 전에 독립 추정치를 만드는 앵커링 방지 절차입니다.",
      "category":"경제심리학",
      "tags":["앵커링","목표가격","독립추정","가격판단"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 훈련 04 · 앵커링",
      "content_blocks":[
        {"kind":"paragraph","text":"‘정가 30만원, 오늘 12만원’이라는 문구를 본 뒤에는 12만원이 싸게 느껴집니다. 주식에서도 52주 최고가, 공모가, 애널리스트 목표가격이 현재 가치 판단의 출발점이 됩니다."},
        {"kind":"heading","text":"첫 숫자는 조용히 기준이 된다"},
        {"kind":"paragraph","text":"앵커링은 초기 숫자에서 충분히 멀리 조정하지 못하는 경향입니다. 앵커가 관련 없는 숫자여도 추정에 영향을 줄 수 있고, 관련성이 있어 보이는 시장 숫자는 더 강하게 작동합니다."},
        {"kind":"paragraph","text":"문제는 목표가격 자체가 아니라 순서입니다. 외부 숫자를 먼저 보면 이후 분석이 독립 평가가 아니라 그 숫자를 정당화하는 조정 과정으로 바뀔 수 있습니다."},
        {"kind":"callout","title":"순서를 바꾸는 한 줄","text":"현재가·최고가·목표가를 가린 뒤, 매출·현금흐름·위험 가정만으로 범위를 먼저 적으세요. 그다음 외부 숫자와 차이를 설명합니다."},
        {"kind":"heading","text":"앵커가 정보일 때도 있다"},
        {"kind":"paragraph","text":"시장가격은 참여자 정보를 반영하므로 무시할 숫자는 아닙니다. 다만 독립 추정 후 비교해야 차이가 새로운 정보 때문인지 단순한 끌림 때문인지 구분할 수 있습니다."},
        {"kind":"list","items":["외부 가격을 보기 전 상·중·하 범위를 만든다","각 범위를 만든 가정을 적는다","앵커와 내 추정의 차이를 설명한다","설명할 수 없는 조정은 보류한다"]},
        {"kind":"heading","text":"정확한 한 점보다 정직한 범위"},
        {"kind":"paragraph","text":"불확실한 미래를 한 숫자로 표현하면 정밀해 보이지만 오차를 숨깁니다. 범위와 조건을 쓰면 앵커에서 얼마나 조정했는지가 아니라 어떤 가정이 결과를 움직였는지 볼 수 있습니다."}
      ],
      "thought_experiment":{"title":"숫자를 가린 두 번의 평가","prompt":"같은 상품을 정가 표시가 있는 화면과 없는 화면에서 각각 평가한다고 가정합니다. 지불의향이 달라진다면 무엇이 가치 판단에 들어왔습니까?","choices":["상품 효용","할인 폭","둘 다 분리하기 어렵다"],"reflection":"가격을 가렸을 때도 유지되는 구매 이유를 세 가지 적어보세요."},
      "practice":{"title":"블라인드 범위 추정","minutes":6,"steps":["판단할 자산이나 상품을 하나 고른다","시장가격과 정가를 가린다","가정 세 개와 가치 범위를 적는다","외부 숫자를 공개하고 차이를 설명한다"],"rule_template":"외부 숫자 ___를 보기 전에 내 범위 ___~___를 먼저 만든다."},
      "source_notes":[{"title":"Judgment under Uncertainty: Heuristics and Biases","authors":"Amos Tversky, Daniel Kahneman","year":1974,"url":"https://doi.org/10.1126/science.185.4157.1124","note":"대표성·가용성·앵커링과 조정 휴리스틱이 체계적 오류를 낳는 과정을 정리한다."},{"title":"Insensitivity to Future Consequences Following Damage to Human Prefrontal Cortex","authors":"Antoine Bechara et al.","year":1994,"url":"https://doi.org/10.1016/0010-0277(94)90018-3","note":"불확실한 선택에서 피드백과 미래 결과를 통합하는 과정의 신경심리학적 근거를 제공한다."}]
    },
    {
      "ordinal":5,
      "slug":"mental-accounting-money-fungibility",
      "title":"보너스 통장과 월급 통장의 돈은 정말 다른가",
      "subtitle":"돈에 붙인 이름이 소비와 위험 선택을 바꾸는 심리적 회계",
      "excerpt":"같은 10만원도 월급, 보너스, 투자수익이라는 이름에 따라 다르게 씁니다. 돈의 출처 대신 전체 목적을 기준으로 재배치하는 연습입니다.",
      "category":"소비자심리학",
      "tags":["심리적회계","보너스","예산","대체가능성"],
      "reading_minutes":7,
      "difficulty":"입문",
      "hero_kicker":"판단 훈련 05 · 심리적 회계",
      "content_blocks":[
        {"kind":"paragraph","text":"월급에서 10만원을 쓰는 일은 망설이면서 카드 포인트나 투자수익 10만원은 쉽게 소비합니다. 화폐의 구매력은 같지만 마음속 장부는 돈의 출처에 서로 다른 사용 허가를 붙입니다."},
        {"kind":"heading","text":"이름표가 선택을 바꾼다"},
        {"kind":"paragraph","text":"심리적 회계는 돈과 결과를 별도 계정으로 분류하고 평가하는 방식입니다. 예산 관리에는 도움이 되지만, 전체 자산 관점에서는 동일한 돈을 다르게 취급하는 오류를 낳을 수 있습니다."},
        {"kind":"paragraph","text":"‘수익금이니까 괜찮다’며 위험을 늘리거나, 저축이 있으면서 높은 카드빚을 유지하는 선택이 예입니다. 계정 간 벽이 이자율과 위험을 가릴 때 비용이 생깁니다."},
        {"kind":"callout","title":"출처를 지우는 질문","text":"이 10만원이 월급에서 왔다면 같은 사용을 하겠습니까? 반대로 필요한 지출이라면 보너스가 없어도 실행했겠습니까?"},
        {"kind":"heading","text":"좋은 이름표도 있다"},
        {"kind":"paragraph","text":"생활비·비상금·장기저축을 나누는 것은 자기통제에 유용할 수 있습니다. 문제는 이름표가 목적을 돕는지, 높은 이자와 과도한 위험을 못 보게 하는지입니다."},
        {"kind":"list","items":["모든 계정의 순자산과 금리를 한 화면에 적는다","보너스와 수익금에도 기본 배분 규칙을 적용한다","계정 이동을 막는 실제 비용이 있는지 확인한다","목적 없는 잔액은 전체 우선순위로 재배치한다"]},
        {"kind":"heading","text":"돈의 출처보다 돈의 임무"},
        {"kind":"paragraph","text":"합리적인 예산은 모든 돈을 한데 섞는 것이 아니라, 각 계정의 임무를 전체 목표와 연결하는 것입니다. 출처가 아니라 위험, 기한, 기회비용이 배분을 결정해야 합니다."}
      ],
      "thought_experiment":{"title":"예상 밖의 20만원","prompt":"환급금 20만원과 초과근무 수당 20만원이 같은 날 들어왔습니다. 두 돈을 다르게 쓰고 싶다면 그 이유는 경제적 차이입니까, 이름표입니까?","choices":["둘 다 같은 규칙으로 배분","환급금만 소비","수당만 소비"],"reflection":"각 선택에서 실제로 달라지는 금리·세금·기한이 있는지 적어보세요."},
      "practice":{"title":"통합 장부 7분","minutes":7,"steps":["현금·저축·빚·투자 계정을 한 줄씩 적는다","각 계정의 금리와 위험을 표시한다","이름을 가리고 우선순위를 다시 매긴다","보너스 배분 규칙을 미리 정한다"],"rule_template":"돈의 출처와 관계없이 ___%는 ___, ___%는 ___에 배분한다."},
      "source_notes":[{"title":"Mental Accounting and Consumer Choice","authors":"Richard H. Thaler","year":1985,"url":"https://doi.org/10.1287/mksc.4.3.199","note":"거래효용과 가계예산을 포함한 심리적 회계 모형을 제시한다."},{"title":"The Red and the Black: Mental Accounting of Savings and Debt","authors":"Drazen Prelec, George Loewenstein","year":1998,"url":"https://doi.org/10.1287/mksc.17.1.4","note":"저축과 부채를 동시에 보유하는 현상을 이중기입 심리회계로 설명한다."}]
    },
    {
      "ordinal":6,
      "slug":"pain-of-paying-digital-wallet",
      "title":"결제가 보이지 않을수록 소비의 브레이크도 흐려진다",
      "subtitle":"간편결제와 구독에서 ‘지불의 고통’을 다시 보이게 만드는 법",
      "excerpt":"결제와 소비가 시간적으로 분리되면 가격 신호가 약해집니다. 불편을 늘리지 않으면서 비용을 다시 인식하는 장치를 설계합니다.",
      "category":"소비자심리학",
      "tags":["지불의고통","간편결제","구독","결제분리"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 훈련 06 · 결제의 고통",
      "content_blocks":[
        {"kind":"paragraph","text":"버튼 한 번으로 결제하고 다음 달에 카드대금을 합산해 보면, 구매 순간에는 가격이 거의 느껴지지 않습니다. 편리함은 시간을 줄이지만 비용과 소비의 연결도 약하게 만들 수 있습니다."},
        {"kind":"heading","text":"가격은 숫자이자 감각이다"},
        {"kind":"paragraph","text":"Prelec과 Loewenstein은 소비의 즐거움과 지불의 고통이 서로 연결되는 방식을 설명했습니다. 결제가 소비와 분리되면 즉각적인 고통은 줄지만, 자기통제를 돕는 가격 신호도 약해질 수 있습니다."},
        {"kind":"paragraph","text":"구독은 이 분리를 더 길게 만듭니다. 처음 결제 후 매달 자동 갱신되면 사용 여부를 다시 선택하지 않아도 비용이 나갑니다. 작은 금액의 반복은 총액을 보이지 않게 합니다."},
        {"kind":"callout","title":"편리함을 없애지 않고 신호만 복구하기","text":"결제 전 ‘월 금액’ 대신 ‘연간 총액’과 사용 1회당 비용을 표시하세요. 자동결제일 하루 전 알림을 두면 다시 선택할 기회가 생깁니다."},
        {"kind":"heading","text":"고통이 클수록 좋은 것은 아니다"},
        {"kind":"paragraph","text":"현금만 쓰거나 모든 결제를 어렵게 만들 필요는 없습니다. 필요한 소비까지 방해하는 과도한 마찰은 시간과 만족을 해칩니다. 목표는 고통을 키우는 것이 아니라 비용 정보를 적시에 보이게 하는 것입니다."},
        {"kind":"list","items":["구독료를 연간 총액으로 환산한다","최근 30일 실제 사용 횟수를 센다","결제일 전 재승인 알림을 둔다","충동구매에는 24시간 대기 규칙을 적용한다"]},
        {"kind":"heading","text":"보이지 않는 돈을 보이게"},
        {"kind":"paragraph","text":"좋은 결제 시스템은 편리하면서도 선택의 결과를 숨기지 않습니다. 총액, 빈도, 다음 결제일을 한 화면에 두면 소비의 즐거움과 예산의 현실을 함께 볼 수 있습니다."}
      ],
      "thought_experiment":{"title":"월 9,900원과 연 118,800원","prompt":"두 표기가 같은 서비스에 대한 지불의향을 다르게 만든다면 어떤 시간 단위가 실제 사용 계획과 더 잘 맞습니까?","choices":["월 금액","연간 총액","사용 1회당 비용"],"reflection":"세 표현을 모두 적고 가장 다른 느낌을 준 표현을 표시하세요."},
      "practice":{"title":"구독 가시화","minutes":6,"steps":["자동결제 세 개를 고른다","연간 총액과 최근 사용 횟수를 계산한다","1회당 비용을 적는다","유지·하향·해지 판단일을 정한다"],"rule_template":"연간 총액 ___원, 월 ___회 이하 사용이면 결제 전에 다시 승인한다."},
      "source_notes":[{"title":"The Red and the Black: Mental Accounting of Savings and Debt","authors":"Drazen Prelec, George Loewenstein","year":1998,"url":"https://doi.org/10.1287/mksc.17.1.4","note":"소비의 즐거움과 지불의 고통이 결제 시점과 결합 방식에 따라 달라지는 모형을 제시한다."},{"title":"Tightwads and Spendthrifts","authors":"Scott I. Rick, Cynthia E. Cryder, George Loewenstein","year":2008,"url":"https://doi.org/10.1086/523285","note":"지불의 고통 차이가 소비성향과 상황별 지출에 연결되는 양상을 분석한다."}]
    },
    {
      "ordinal":7,
      "slug":"myopic-loss-checking-frequency",
      "title":"계좌를 자주 볼수록 장기 계획이 짧아질 수 있다",
      "subtitle":"평가 빈도가 손실회피와 위험 선택을 증폭시키는 방식",
      "excerpt":"장기 투자도 매분 평가하면 단기 손실의 연속으로 경험됩니다. 확인 빈도와 의사결정 빈도를 분리하는 훈련입니다.",
      "category":"행동금융학",
      "tags":["근시안적손실회피","평가빈도","장기투자","알림"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 훈련 07 · 평가 빈도",
      "content_blocks":[
        {"kind":"paragraph","text":"10년 계획으로 시작한 투자도 알림을 매분 받으면 10년짜리 선택으로 느껴지지 않습니다. 화면을 열 때마다 짧은 구간의 손익이 새 결정처럼 다가옵니다."},
        {"kind":"heading","text":"시간 창이 위험의 모양을 바꾼다"},
        {"kind":"paragraph","text":"근시안적 손실회피는 손실에 민감한 사람이 결과를 자주 평가할 때 위험자산을 더 불편하게 느낄 수 있다는 설명입니다. 같은 장기 분포도 짧게 잘라 보면 손실 구간을 더 자주 마주칩니다."},
        {"kind":"paragraph","text":"확인 자체가 나쁜 것은 아닙니다. 레버리지, 마진콜, 만기가 있는 상품은 실시간 관리가 필요합니다. 하지만 장기 포트폴리오를 단기 알림으로 관리하면 투자 기한과 평가 기한이 충돌합니다."},
        {"kind":"callout","title":"확인과 행동을 분리하기","text":"화면은 볼 수 있지만 매매는 정해진 검토일에만 하도록 분리하세요. 예외는 손실한도, 현금수요, 가설 훼손 같은 사전 조건으로 한정합니다."},
        {"kind":"heading","text":"빈도를 낮출 수 없는 상품"},
        {"kind":"paragraph","text":"선물·옵션처럼 위험이 빠르게 변하는 상품은 확인 빈도보다 포지션 크기를 줄이는 것이 먼저입니다. 자주 봐야 안전한 규모라면, 감당 가능한 위험인지 다시 계산해야 합니다."},
        {"kind":"list","items":["투자 기한과 평가 기한을 각각 적는다","가격 알림과 행동 조건을 분리한다","정기 검토일을 달력에 고정한다","예외 행동 조건은 세 개 이하로 둔다"]},
        {"kind":"heading","text":"정보가 아니라 노출량을 관리한다"},
        {"kind":"paragraph","text":"더 자주 본다고 항상 더 많이 아는 것은 아닙니다. 같은 변동을 반복해 보는 것은 정보 추가가 아니라 감정 노출의 증가일 수 있습니다. 판단 빈도는 상품의 위험과 계획의 시간축에 맞춰야 합니다."}
      ],
      "thought_experiment":{"title":"같은 수익률, 다른 화면","prompt":"연간 결과만 보는 계좌와 매일 손익을 보는 계좌의 최종 수익률이 같다면 어느 쪽에서 계획을 더 자주 바꿀 것 같습니까?","choices":["연간 화면","매일 화면","차이 없다"],"reflection":"바꾸고 싶은 충동이 새 정보 때문인지 단기 손실 노출 때문인지 적어보세요."},
      "practice":{"title":"평가 달력 만들기","minutes":7,"steps":["보유 항목별 투자 기한을 적는다","필요한 확인 빈도를 정한다","매매 가능한 검토일을 따로 정한다","예외 조건과 행동을 연결한다"],"rule_template":"가격은 ___마다 확인하지만, 매매는 ___ 또는 예외 조건 ___에서만 한다."},
      "source_notes":[{"title":"Myopic Loss Aversion and the Equity Premium Puzzle","authors":"Shlomo Benartzi, Richard H. Thaler","year":1995,"url":"https://doi.org/10.2307/2118511","note":"손실회피와 잦은 평가의 결합이 장기 위험 선택에 미치는 효과를 모형화한다."},{"title":"An Experiment on Risk Taking and Evaluation Periods","authors":"Uri Gneezy, Jan Potters","year":1997,"url":"https://doi.org/10.1162/003355397555217","note":"평가 기간이 위험 투자 선택에 영향을 주는지 실험으로 검토한다."}]
    },
    {
      "ordinal":8,
      "slug":"house-money-risk-budget",
      "title":"수익금도 내 돈이다: ‘공짜 돈’이 위험 한도를 무너뜨릴 때",
      "subtitle":"직전 이익과 현재 베팅을 한 장부에서 분리하는 위험예산",
      "excerpt":"수익 직후에는 잃어도 본전이라는 느낌이 위험을 키웁니다. 직전 결과와 다음 선택을 분리해 일정한 위험예산을 유지합니다.",
      "category":"행동재무학",
      "tags":["하우스머니효과","위험예산","직전수익","포지션크기"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 훈련 08 · 하우스머니 효과",
      "content_blocks":[
        {"kind":"paragraph","text":"큰 수익을 낸 다음 거래에서 평소보다 계약 수를 늘리는 일이 있습니다. ‘어차피 번 돈 일부’라는 표현은 수익금을 내 자산이 아닌 카지노의 돈처럼 느끼게 합니다."},
        {"kind":"heading","text":"직전 결과가 다음 위험의 가격을 바꾼다"},
        {"kind":"paragraph","text":"하우스머니 효과는 앞선 이익 뒤에 위험감수가 커지는 현상을 가리킵니다. 반대로 손실 뒤에는 본전 기회를 특별히 매력적으로 보는 손익분기 효과가 나타날 수 있습니다."},
        {"kind":"paragraph","text":"규범적으로 다음 선택은 증가분의 결과만 평가해야 합니다. 직전 수익은 감당 능력을 실제로 높일 수 있지만, 그만큼 위험한 선택이 자동으로 좋아지는 것은 아닙니다."},
        {"kind":"callout","title":"수익을 먼저 자산으로 편입하기","text":"거래가 끝나는 순간 수익을 총자산에 합산하고 다음 거래의 위험 한도를 동일한 비율 규칙으로 다시 계산하세요. ‘공짜 돈’ 항목을 만들지 않습니다."},
        {"kind":"heading","text":"위험을 늘릴 수 있는 합리적 이유"},
        {"kind":"paragraph","text":"총자산 증가로 절대 위험예산이 커지거나, 전략의 검증된 우위가 개선되었다면 규모를 조정할 수 있습니다. 단지 기분이 가벼워졌다는 이유와 구분하려면 사전 공식이 필요합니다."},
        {"kind":"list","items":["직전 손익을 총자산에 즉시 합산한다","거래당 최대 손실 비율을 고정한다","연속 수익 뒤 규모 상한을 둔다","본전이라는 표현을 계획서에서 제거한다"]},
        {"kind":"heading","text":"결과가 아니라 규칙이 규모를 정한다"},
        {"kind":"paragraph","text":"연승은 전략의 증거일 수도 우연일 수도 있습니다. 표본이 충분하지 않은 상태에서 규모를 키우면 운을 실력으로 오인합니다. 다음 위험은 직전 감정이 아니라 장기 위험예산이 결정해야 합니다."}
      ],
      "thought_experiment":{"title":"수익 출처를 가린 선택","prompt":"동일한 총자산에서 100만원이 거래수익인지 월급인지 모른다면 다음 거래 규모를 다르게 정해야 합니까?","choices":["같게 정한다","수익금이면 늘린다","월급이면 늘린다"],"reflection":"다르게 정했다면 실제 감당 능력의 차이인지 이름표의 차이인지 적어보세요."},
      "practice":{"title":"위험예산 재설정","minutes":6,"steps":["현재 총자산을 적는다","거래당 허용 손실 비율을 정한다","직전 손익을 합산해 금액을 계산한다","연승·연패와 무관한 상한을 적는다"],"rule_template":"직전 결과와 무관하게 총자산의 ___%만 한 거래의 최대 손실로 허용한다."},
      "source_notes":[{"title":"Gambling with the House Money and Trying to Break Even","authors":"Richard H. Thaler, Eric J. Johnson","year":1990,"url":"https://doi.org/10.1287/mnsc.36.6.643","note":"앞선 이익과 손실이 이후 위험 선택에 미치는 하우스머니·손익분기 효과를 실험한다."},{"title":"Mental Accounting and Consumer Choice","authors":"Richard H. Thaler","year":1985,"url":"https://doi.org/10.1287/mksc.4.3.199","note":"결과를 별도 계정으로 부호화하는 심리적 회계의 기초를 제시한다."}]
    },
    {
      "ordinal":9,
      "slug":"choice-overload-investment-products",
      "title":"선택지가 많아질수록 비교표는 짧아져야 한다",
      "subtitle":"ETF·보험·쇼핑 옵션의 선택 과부하를 기준 세 개로 줄이는 법",
      "excerpt":"상품이 많으면 더 좋은 선택이 가능해 보이지만 결정 피로와 후회를 키울 수 있습니다. 먼저 기준을 정해 선택 집합을 줄입니다.",
      "category":"소비자심리학",
      "tags":["선택과부하","결정피로","ETF","비교기준"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 훈련 09 · 선택 과부하",
      "content_blocks":[
        {"kind":"paragraph","text":"검색창에 ‘미국 주식 ETF’를 입력하면 비슷해 보이는 상품이 끝없이 나옵니다. 선택지가 많으면 최적을 찾을 가능성이 커지는 동시에 비교 비용과 놓친 대안에 대한 후회도 커집니다."},
        {"kind":"heading","text":"더 많은 선택이 항상 더 나은가"},
        {"kind":"paragraph","text":"Iyengar와 Lepper의 연구는 많은 선택지가 관심을 끌 수 있지만 실제 선택과 만족을 낮출 가능성을 보여줬습니다. 다만 선택 과부하는 상황과 전문성에 따라 달라지므로 ‘항상 적을수록 좋다’는 법칙은 아닙니다."},
        {"kind":"paragraph","text":"핵심은 상품 수가 아니라 비교 구조입니다. 목표가 불명확한 상태에서 수십 개 속성을 동시에 최적화하려 하면 눈에 띄는 브랜드나 최근 수익률로 도피하기 쉽습니다."},
        {"kind":"callout","title":"상품보다 탈락 기준을 먼저","text":"반드시 필요한 기준 세 개와 즉시 탈락 기준 두 개를 먼저 정하세요. 기준을 통과한 후보만 세 개 이하로 남깁니다."},
        {"kind":"heading","text":"충분히 좋은 선택의 가치"},
        {"kind":"paragraph","text":"비용이 낮고 목적에 맞으며 이해 가능한 상품이라면, 미세한 차이를 찾는 시간보다 실행과 유지가 더 중요할 수 있습니다. 완벽한 선택을 찾느라 결정을 미루는 것도 비용입니다."},
        {"kind":"list","items":["목표와 보유기간을 먼저 쓴다","필수 기준 세 개를 정한다","탈락 기준 두 개로 후보를 줄인다","최종 후보는 같은 단위로 비교한다"]},
        {"kind":"heading","text":"선택 후에는 재검색을 멈춘다"},
        {"kind":"paragraph","text":"선택 직후 계속 검색하면 선택하지 않은 장점만 보이고 현재 선택의 단점이 커 보입니다. 재검토 날짜와 조건을 정해두면 불필요한 비교를 줄이고 중요한 변화에만 반응할 수 있습니다."}
      ],
      "thought_experiment":{"title":"6개와 30개 후보","prompt":"기준이 명확한 6개 후보와 기준 없이 제시된 30개 후보 중 어느 쪽에서 더 일관된 결정을 할 수 있습니까?","choices":["6개","30개","전문성에 따라 다르다"],"reflection":"당신에게 후보 수보다 더 중요한 비교 기준 세 개를 적어보세요."},
      "practice":{"title":"3-2-3 비교법","minutes":7,"steps":["필수 기준 세 개를 적는다","탈락 기준 두 개를 적는다","후보를 세 개 이하로 줄인다","재검토 날짜를 정하고 검색을 종료한다"],"rule_template":"___ 목적에서 ___·___·___를 통과한 세 후보만 비교한다."},
      "source_notes":[{"title":"When Choice Is Demotivating: Can One Desire Too Much of a Good Thing?","authors":"Sheena S. Iyengar, Mark R. Lepper","year":2000,"url":"https://doi.org/10.1037/0022-3514.79.6.995","note":"선택지 수가 동기와 실제 선택, 만족에 미치는 영향을 세 실험으로 검토한다."},{"title":"Choice Overload: A Conceptual Review and Meta-Analysis","authors":"Benjamin Scheibehenne, Rainer Greifeneder, Peter M. Todd","year":2010,"url":"https://doi.org/10.1086/651235","note":"선택 과부하 효과가 맥락에 따라 달라짐을 메타분석으로 정리한다."}]
    },
    {
      "ordinal":10,
      "slug":"attention-stock-selection",
      "title":"눈에 띈 종목은 좋은 종목이 아니라 검색을 통과한 종목일 뿐이다",
      "subtitle":"급등주·뉴스 종목이 매수 후보가 되는 주의 편향의 구조",
      "excerpt":"뉴스와 급등률은 수천 종목 중 일부만 보이게 합니다. 관심을 끈 이유와 투자 근거를 분리해 후보군을 다시 만듭니다.",
      "category":"행동금융학",
      "tags":["주의편향","급등주","뉴스","후보선정"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 훈련 10 · 주의 편향",
      "content_blocks":[
        {"kind":"paragraph","text":"오늘 가장 많이 오른 종목과 속보에 등장한 기업은 쉽게 매수 후보가 됩니다. 그러나 눈에 띈 것은 기대수익이 높다는 증거가 아니라, 우리의 제한된 주의 관문을 통과했다는 사실입니다."},
        {"kind":"heading","text":"선호 이전에 후보군이 결정된다"},
        {"kind":"paragraph","text":"개인투자자는 살 수 있는 종목이 너무 많아 모두 분석하기 어렵습니다. Barber와 Odean은 뉴스, 비정상적 거래량, 극단적 수익률로 주의를 끈 종목에 개인의 순매수가 몰리는 경향을 분석했습니다."},
        {"kind":"paragraph","text":"매도는 이미 보유한 좁은 목록에서 고르지만 매수는 수천 종목 중 골라야 합니다. 그래서 관심이 먼저 후보군을 만들고, 분석은 그 뒤에 이루어집니다. 분석이 정교해도 후보군이 편향되면 결론도 제한됩니다."},
        {"kind":"callout","title":"발견 이유와 보유 이유를 분리하기","text":"‘뉴스에서 봤다’는 발견 경로입니다. 매수 이유에는 가격, 현금흐름, 위험, 반증 조건처럼 발견 경로와 독립된 근거만 적으세요."},
        {"kind":"heading","text":"뉴스가 실제 정보일 때"},
        {"kind":"paragraph","text":"주의를 끈 사건이 가치에 중요한 새 정보일 수 있습니다. 문제는 뉴스가 아니라 비교군 부재입니다. 같은 조건의 조용한 기업과 비교해야 정보의 가치와 관심 프리미엄을 구분할 수 있습니다."},
        {"kind":"list","items":["발견 경로를 한 줄로 적는다","동종 비교군 두 개를 강제로 추가한다","뉴스가 현금흐름을 바꾸는 경로를 적는다","하루 뒤에도 근거가 유지되는지 재검토한다"]},
        {"kind":"heading","text":"보이는 것 밖에서 후보를 만든다"},
        {"kind":"paragraph","text":"체계적 스크리닝은 완벽하지 않지만 주의가 만든 후보군을 넓힙니다. 최근 급등률을 기준에서 빼고 목적에 맞는 재무·위험 조건으로 먼저 걸러내면, 관심과 가치의 순서를 뒤집을 수 있습니다."}
      ],
      "thought_experiment":{"title":"뉴스 없는 쌍둥이 기업","prompt":"재무와 전망이 같은 두 기업 중 하나만 오늘 뉴스에 등장했습니다. 뉴스 내용이 가치와 무관하다면 어느 기업을 더 자세히 볼 이유가 있습니까?","choices":["뉴스 기업","조용한 기업","둘을 같은 기준으로 비교"],"reflection":"오늘 본 투자 후보의 발견 경로를 적고 그것이 기대가치와 연결되는지 설명하세요."},
      "practice":{"title":"주의 편향 역검색","minutes":7,"steps":["오늘 눈에 띈 종목 하나를 적는다","발견 경로와 투자 근거를 분리한다","동종 비교군 두 개를 찾는다","동일 기준으로 세 종목을 평가한다"],"rule_template":"뉴스로 발견한 후보는 ___시간 후 비교군 ___개와 같은 기준으로 다시 평가한다."},
      "source_notes":[{"title":"All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors","authors":"Brad M. Barber, Terrance Odean","year":2008,"url":"https://doi.org/10.1093/rfs/hhm079","note":"뉴스·거래량·극단 수익률로 주의를 끈 종목에 개인투자자의 매수가 집중되는지 분석한다."},{"title":"Judgment under Uncertainty: Heuristics and Biases","authors":"Amos Tversky, Daniel Kahneman","year":1974,"url":"https://doi.org/10.1126/science.185.4157.1124","note":"가용성이 확률과 빈도 판단을 왜곡할 수 있음을 설명한다."}]
    },
    {
      "ordinal":11,
      "slug":"present-bias-subscription-renewal",
      "title":"오늘의 편리함이 내일의 자동결제를 이기는 이유",
      "subtitle":"현재 편향을 의지 대신 사전 약속으로 다루는 소비 설계",
      "excerpt":"지금의 작은 편익은 크게 느껴지고 미래 비용은 희미해집니다. 구독·할부·저축 결정을 미래의 나에게 떠넘기지 않는 약속 장치입니다.",
      "category":"행동경제학",
      "tags":["현재편향","자동결제","자기통제","약속장치"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 훈련 11 · 현재 편향",
      "content_blocks":[
        {"kind":"paragraph","text":"무료 체험을 시작할 때는 다음 달 전에 해지할 계획입니다. 그러나 해지는 미래의 작은 수고가 되고, 오늘은 즉시 얻는 편리함이 큽니다. 시간이 지나면 같은 사람이 다른 선택을 합니다."},
        {"kind":"heading","text":"미래의 나는 오늘의 나와 협상한다"},
        {"kind":"paragraph","text":"현재 편향은 가까운 보상과 비용에 불균형하게 큰 가중치를 두는 경향입니다. Laibson의 모형은 시간에 따라 선호가 달라질 때 사람들이 미래 선택을 제한하는 약속 장치를 원할 수 있음을 보여줍니다."},
        {"kind":"paragraph","text":"문제는 미래의 내가 더 성실할 것이라는 낙관입니다. 해지, 저축, 기록처럼 즉시 비용이 드는 행동은 미루고, 쇼핑·게임·레버리지처럼 즉시 보상이 있는 행동은 앞당기기 쉽습니다."},
        {"kind":"callout","title":"미래 계획을 오늘 실행으로 바꾸기","text":"무료 체험을 시작하는 순간 해지 검토 일정을 등록하고, 저축은 월말 잔액이 아니라 급여일 자동이체로 설정하세요."},
        {"kind":"heading","text":"약속 장치의 비용"},
        {"kind":"paragraph","text":"모든 유동성을 잠그면 예상치 못한 상황에 대응하기 어렵습니다. 좋은 약속 장치는 취소 가능성과 마찰의 강도를 목적에 맞춥니다. 비상자금은 유동적으로, 충동 예산은 제한적으로 설계할 수 있습니다."},
        {"kind":"list","items":["미래 행동의 날짜와 시간을 지금 정한다","즉시 보상 앞에 짧은 대기시간을 둔다","저축은 소득 직후 자동화한다","약속을 깰 수 있는 합리적 예외를 적는다"]},
        {"kind":"heading","text":"의지보다 환경이 오래간다"},
        {"kind":"paragraph","text":"자기통제 실패를 성격 문제로만 보면 매번 같은 싸움을 반복합니다. 선택 환경을 바꾸면 미래의 내가 결정을 다시 시작할 필요가 줄어듭니다. 좋은 계획은 미래의 나를 믿는 대신 돕습니다."}
      ],
      "thought_experiment":{"title":"지금의 나와 한 달 뒤의 나","prompt":"오늘 1만원 할인과 한 달 뒤 2만원 절약 중 무엇을 고르겠습니까? 한 달 뒤 두 선택이 모두 미래라면 답이 달라집니까?","choices":["오늘 할인","한 달 뒤 절약","조건에 따라 다름"],"reflection":"시간 위치만 바뀌었는데 선호가 달라졌다면 현재 편향의 신호일 수 있습니다."},
      "practice":{"title":"사전 약속 하나 만들기","minutes":7,"steps":["반복해 미루는 돈 관련 행동을 고른다","즉시 비용과 미래 편익을 적는다","날짜·금액·행동을 자동화한다","취소가 필요한 합리적 예외를 정한다"],"rule_template":"___일 ___시에 ___원을 자동으로 ___하며, 예외는 ___일 때만 허용한다."},
      "source_notes":[{"title":"Golden Eggs and Hyperbolic Discounting","authors":"David Laibson","year":1997,"url":"https://doi.org/10.1162/003355397555253","note":"시간 비일관적 선호와 자기통제를 위한 약속 장치의 역할을 경제모형으로 분석한다."},{"title":"Doing It Now or Later","authors":"Ted O'Donoghue, Matthew Rabin","year":1999,"url":"https://doi.org/10.1257/aer.89.1.103","note":"현재 편향과 자기통제 인식이 미루기 및 즉시 보상 행동에 미치는 효과를 분석한다."}]
    }
  ]
  $articles$::jsonb) as x(
    ordinal integer,
    slug text,
    title text,
    subtitle text,
    excerpt text,
    category text,
    tags jsonb,
    reading_minutes integer,
    difficulty text,
    hero_kicker text,
    content_blocks jsonb,
    thought_experiment jsonb,
    practice jsonb,
    source_notes jsonb
  )
)
insert into public.articles (
  slug, version, is_current, status, title, subtitle, excerpt, category, tags,
  reading_minutes, difficulty, hero_kicker, content_blocks, thought_experiment,
  practice, source_notes, author_agent, published_at
)
select
  slug, 1, true, 'PUBLISHED', title, subtitle, excerpt, category,
  array(select jsonb_array_elements_text(tags)), reading_minutes, difficulty,
  hero_kicker, content_blocks, thought_experiment, practice, source_notes,
  'codex:manual-research-batch-01', now() - ((11 - ordinal) * interval '1 minute')
from batch
on conflict (slug, version) do update
set is_current = true,
    status = 'PUBLISHED',
    title = excluded.title,
    subtitle = excluded.subtitle,
    excerpt = excluded.excerpt,
    category = excluded.category,
    tags = excluded.tags,
    reading_minutes = excluded.reading_minutes,
    difficulty = excluded.difficulty,
    hero_kicker = excluded.hero_kicker,
    content_blocks = excluded.content_blocks,
    thought_experiment = excluded.thought_experiment,
    practice = excluded.practice,
    source_notes = excluded.source_notes,
    author_agent = excluded.author_agent,
    published_at = excluded.published_at;

commit;
