begin;

with batch as (
  select * from jsonb_to_recordset($articles$
  [
    {
      "ordinal":2,
      "slug":"sunk-cost-next-decision",
      "title":"이미 쓴 돈은 다음 결정을 지시할 권리가 없다",
      "subtitle":"손실을 인정하지 않으려는 마음과 미래 가치를 분리하는 법",
      "excerpt":"수수료와 시간, 옵션 프리미엄을 이미 지불했다는 이유로 나쁜 선택을 연장할 때가 있습니다. 매몰비용 연구가 과거의 지출과 미래의 가치를 어떻게 구분하는지 살펴봅니다.",
      "category":"행동경제학",
      "tags":["매몰비용","추가투입","옵션","철수규칙"],
      "reading_minutes":7,
      "difficulty":"입문",
      "hero_kicker":"판단 연구 02 · 매몰비용",
      "content_blocks":[
        {"kind":"paragraph","text":"만기가 가까운 옵션이 큰 손실을 기록하고 있습니다. 처음 지불한 프리미엄이 아까워 추가 계약을 사면 평균단가가 낮아진다는 생각이 듭니다. 그러나 이미 지불해 되돌릴 수 없는 비용은 오늘의 추가 매수가 좋은지 알려주지 않습니다."},
        {"kind":"heading","text":"과거의 비용이 미래의 표처럼 보일 때"},
        {"kind":"paragraph","text":"매몰비용 효과는 돈·시간·노력을 이미 투입했다는 사실 때문에 활동을 계속하려는 경향입니다. 사람은 중단을 낭비의 인정처럼 느끼기 쉽고, 계속하면 과거의 선택을 정당화할 수 있다고 기대합니다."},
        {"kind":"heading","text":"실제 연구는 어떻게 매몰비용을 만들었나"},
        {"kind":"paragraph","text":"Arkes와 Blumer의 대표적 현장연구는 극장 시즌권 구매자를 정상가격 집단과 서로 다른 할인 집단으로 나눈 뒤 실제 관람 횟수를 추적했습니다. 초기에 더 많이 지불한 집단이 첫 6개월 동안 더 자주 관람한 결과를 매몰비용 효과로 해석했습니다. 다만 무작위 배정의 세부와 표본 규모, 관람을 효용이 아니라 의무로 볼 수 있는지 등 외적 타당성 문제도 함께 살펴야 합니다."},
        {"kind":"paragraph","text":"하지만 다음 결정의 비교 대상은 ‘지금 멈추기’와 ‘지금부터 더 투입하기’입니다. 최초 비용을 되찾을 가능성이 아니라 추가 비용 이후의 결과 분포, 남은 시간, 대안의 기회비용을 비교해야 합니다."},
        {"kind":"callout","title":"독립된 새 결정으로 바꾸기","text":"이 포지션을 오늘 처음 발견했고 과거 지출이 0원이라면, 현재 가격에 같은 추가 투입을 하겠습니까? 아니오라면 과거 비용이 판단에 끼어든 것입니다."},
        {"kind":"heading","text":"계속하는 것이 합리적인 경우"},
        {"kind":"paragraph","text":"중단이 항상 정답은 아닙니다. 새 정보로 성공확률이 높아졌거나, 철수비용이 크거나, 추가 투입의 기대가치가 대안보다 높다면 계속할 수 있습니다. 핵심은 ‘이미 많이 썼다’가 아니라 ‘지금부터의 순편익이 크다’는 근거입니다."},
        {"kind":"list","items":["회수 불가능한 과거 비용을 따로 적는다","지금부터 드는 추가 비용과 최악의 손실을 적는다","같은 자원으로 가능한 최선의 대안을 적는다","계속 조건과 중단 조건을 숫자로 정한다"]},
        {"kind":"heading","text":"낭비를 줄이는 진짜 방법"},
        {"kind":"paragraph","text":"나쁜 계획을 연장하면 과거의 낭비가 사라지는 것이 아니라 미래 비용이 더해집니다. 합리성은 과거의 나를 무죄로 만드는 일이 아니라, 현재의 내가 다음 손실을 제한하는 일입니다."}
      ],
      "thought_experiment":{"title":"과거 장부를 보지 못하는 투자위원회","prompt":"두 위원회가 동일한 사업의 미래 현금흐름 자료를 받습니다. 한 위원회만 이미 30억원을 썼다는 사실을 압니다. 두 집단의 추가투자율이 다르다면 그 차이는 정보의 질 때문일까요, 과거 선택을 정당화하려는 동기 때문일까요?","choices":["매몰비용 효과가 주된 원인이다","과거 지출도 미래 성공확률의 신호일 수 있다","설계만으로는 두 설명을 분리하기 어렵다"],"reflection":"과거 지출액과 사업의 질에 관한 정보를 독립적으로 조작한다면 어떤 2×2 실험을 설계할 수 있을지 생각해보세요."},
      "practice":{"title":"세미나에서 더 생각해볼 쟁점","minutes":0,"steps":["시즌권 가격과 관람 횟수 사이에 매몰비용 외의 설명이 가능한지 검토한다","과거 투입액이 프로젝트 품질의 신호가 되는 상황을 구분한다","중단 결정에서 책임소재와 평판이 어떤 교란변수가 되는지 생각한다","투자 포지션을 오늘 새로 받았다는 반사실이 판단을 얼마나 바꾸는지 비교한다"],"rule_template":"과거 지출은 미래 현금흐름을 바꾸는 정보일 때만 다음 결정에 포함한다."},
      "source_notes":[{"title":"The Psychology of Sunk Cost","authors":"Hal R. Arkes, Catherine Blumer","year":1985,"url":"https://doi.org/10.1016/0749-5978(85)90049-4","note":"이미 투입한 돈·시간·노력이 활동 지속을 높이는 매몰비용 효과를 현장 및 설문 연구로 보여준다."},{"title":"Prospect Theory: An Analysis of Decision under Risk","authors":"Daniel Kahneman, Amos Tversky","year":1979,"url":"https://doi.org/10.2307/1914185","note":"손실 영역의 위험추구와 기준점 의존적 평가를 설명하는 토대를 제공한다."}]
    },
    {
      "ordinal":3,
      "slug":"overconfidence-trading-frequency",
      "title":"확신이 커질수록 주문 버튼에서 한 걸음 멀어져야 한다",
      "subtitle":"예측 정확도와 거래 횟수를 분리하는 과잉확신 점검법",
      "excerpt":"정보를 많이 봤다는 느낌은 예측력이 높아졌다는 증거가 아닙니다. 과잉확신을 계좌자료로 연구한 방식과 인과 해석의 한계를 살펴봅니다.",
      "category":"행동재무학",
      "tags":["과잉확신","과잉거래","예측","수수료"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 연구 03 · 과잉확신",
      "content_blocks":[
        {"kind":"paragraph","text":"뉴스, 차트, 커뮤니티 의견을 충분히 확인한 날에는 거래하지 않는 것이 더 어렵습니다. 정보량이 늘수록 ‘무언가 해야 한다’는 감각이 커지지만, 정보량과 예측 정확도는 같은 변수가 아닙니다."},
        {"kind":"heading","text":"확신은 측정값이 아니라 느낌일 수 있다"},
        {"kind":"paragraph","text":"과잉확신은 자신의 정보 정확도나 통제력을 실제보다 높게 평가하는 현상입니다. 투자에서는 작은 차이를 확실한 우위로 해석하고 거래 빈도와 포지션 크기를 늘리는 통로가 됩니다."},
        {"kind":"paragraph","text":"Barber와 Odean의 계좌자료 연구는 더 활발한 거래와 낮은 순성과가 함께 나타날 수 있음을 보여줍니다. 이 결과가 모든 잦은 거래가 나쁘다는 뜻은 아니지만, 수수료·스프레드·세금이라는 확정 비용을 이길 만큼 우위가 있는지 묻게 합니다."},
        {"kind":"heading","text":"실험이 아니라 계좌자료를 비교한 연구"},
        {"kind":"paragraph","text":"이 연구는 참가자에게 과잉확신을 유도한 실험이 아니라 대형 할인증권사의 가구별 거래기록을 이용한 관찰연구입니다. 연구진은 회전율과 비용 차감 수익률을 비교하고 성별 차이를 과잉확신의 예측과 연결했습니다. 따라서 거래가 많아서 성과가 낮아졌다는 인과와, 원래 성과가 낮거나 전략이 다른 사람이 많이 거래했다는 선택효과를 완전히 같게 취급해서는 안 됩니다."},
        {"kind":"callout","title":"확신도보다 적중률","text":"매 주문 전에 상승·하락·횡보 확률과 확신도를 적고, 20회 뒤 실제 적중률과 비교하세요. 기억이 아니라 기록으로 보정해야 합니다."},
        {"kind":"heading","text":"전문성과 과잉확신을 구별하기"},
        {"kind":"paragraph","text":"전문가는 근거뿐 아니라 오차범위와 실패 조건을 말할 수 있습니다. 반대로 과잉확신은 반증 조건이 흐리고, 성공은 실력으로 실패는 외부 탓으로 분류하는 경향을 보입니다."},
        {"kind":"list","items":["주장의 반대 증거를 한 개 찾는다","예측 확률을 50·60·70%처럼 수치화한다","비용 차감 후 필요한 최소 우위를 계산한다","거래하지 않기 선택도 기록한다"]},
        {"kind":"heading","text":"좋은 무행동도 결정이다"},
        {"kind":"paragraph","text":"시장은 매일 열리지만 모든 날이 의사결정 기회는 아닙니다. 기준을 통과하지 못한 거래를 건너뛰는 것은 소극성이 아니라, 확신과 우위를 구분한 능동적 선택입니다."}
      ],
      "thought_experiment":{"title":"확률 예측자의 자격시험","prompt":"두 사람이 100개 사건에 각각 확률을 붙였습니다. A는 늘 90%라고 말해 70개를 맞혔고, B는 60%라고 말한 사건의 약 60%를 맞혔습니다. 투자위원이라면 정확도, 보정, 식별력 중 무엇을 먼저 보겠습니까?","choices":["더 많이 맞힌 A","확률이 더 잘 보정된 B","손실함수를 정하기 전에는 결정할 수 없다"],"reflection":"예측 품질은 적중률 하나로 결정되지 않습니다. 과도한 확신에 더 큰 벌점을 주는 평가함수와 그렇지 않은 평가함수가 두 사람의 순위를 어떻게 바꿀지 생각해보세요."},
      "practice":{"title":"연구 결과를 읽을 때의 쟁점","minutes":0,"steps":["계좌자료의 회전율과 과잉확신을 같은 개념으로 볼 수 있는지 따진다","거래비용 전·후 성과가 각각 어떤 질문에 답하는지 구분한다","성별 차이를 심리특성의 증거로 해석할 때 필요한 가정을 적는다","실험으로 인과관계를 확인하려면 어떤 무작위 처치가 가능한지 설계한다"],"rule_template":"자신감의 크기와 예측확률의 보정도, 거래 후 성과를 서로 다른 변수로 본다."},
      "source_notes":[{"title":"Boys Will Be Boys: Gender, Overconfidence, and Common Stock Investment","authors":"Brad M. Barber, Terrance Odean","year":2001,"url":"https://doi.org/10.1162/003355301556400","note":"개인투자자 계좌자료에서 과잉확신, 거래 빈도, 순성과의 관계를 분석한다."},{"title":"Trading Is Hazardous to Your Wealth","authors":"Brad M. Barber, Terrance Odean","year":2000,"url":"https://doi.org/10.1111/0022-1082.00226","note":"거래가 가장 활발한 가구의 비용 차감 후 성과를 계좌자료로 검토한다."}]
    },
    {
      "ordinal":4,
      "slug":"anchor-price-independence",
      "title":"목표가격을 보기 전에 내 숫자를 먼저 만들어라",
      "subtitle":"앵커가 분석의 출발점을 점령하지 못하게 하는 순서 설계",
      "excerpt":"첫 가격과 전문가 목표치는 이후 추정을 끌어당깁니다. 외부 숫자를 보기 전에 독립 추정치를 만드는 앵커링 방지 절차입니다.",
      "category":"경제심리학",
      "tags":["앵커링","목표가격","독립추정","가격판단"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 연구 04 · 앵커링",
      "content_blocks":[
        {"kind":"paragraph","text":"‘정가 30만원, 오늘 12만원’이라는 문구를 본 뒤에는 12만원이 싸게 느껴집니다. 주식에서도 52주 최고가, 공모가, 애널리스트 목표가격이 현재 가치 판단의 출발점이 됩니다."},
        {"kind":"heading","text":"첫 숫자는 조용히 기준이 된다"},
        {"kind":"paragraph","text":"앵커링은 초기 숫자에서 충분히 멀리 조정하지 못하는 경향입니다. 앵커가 관련 없는 숫자여도 추정에 영향을 줄 수 있고, 관련성이 있어 보이는 시장 숫자는 더 강하게 작동합니다."},
        {"kind":"heading","text":"무관한 숫자를 앵커로 만든 고전 실험 설계"},
        {"kind":"paragraph","text":"Tversky와 Kahneman의 고전 과제에서는 참가자가 행운의 바퀴로 무작위 숫자를 본 뒤, 유엔 회원국 중 아프리카 국가의 비율이 그 숫자보다 높은지 낮은지 판단하고 최종 추정치를 답했습니다. 무작위 숫자와 정답은 논리적으로 무관하지만 추정치는 앵커 방향으로 움직였습니다. 무작위화가 있어 인과 해석은 강하지만, 지식이 부족한 퀴즈 상황이 실제 가치평가와 얼마나 같은지는 별도의 외적 타당성 질문입니다."},
        {"kind":"paragraph","text":"문제는 목표가격 자체가 아니라 순서입니다. 외부 숫자를 먼저 보면 이후 분석이 독립 평가가 아니라 그 숫자를 정당화하는 조정 과정으로 바뀔 수 있습니다."},
        {"kind":"callout","title":"순서를 바꾸는 한 줄","text":"현재가·최고가·목표가를 가린 뒤, 매출·현금흐름·위험 가정만으로 범위를 먼저 적으세요. 그다음 외부 숫자와 차이를 설명합니다."},
        {"kind":"heading","text":"앵커가 정보일 때도 있다"},
        {"kind":"paragraph","text":"시장가격은 참여자 정보를 반영하므로 무시할 숫자는 아닙니다. 다만 독립 추정 후 비교해야 차이가 새로운 정보 때문인지 단순한 끌림 때문인지 구분할 수 있습니다."},
        {"kind":"list","items":["외부 가격을 보기 전 상·중·하 범위를 만든다","각 범위를 만든 가정을 적는다","앵커와 내 추정의 차이를 설명한다","설명할 수 없는 조정은 보류한다"]},
        {"kind":"heading","text":"정확한 한 점보다 정직한 범위"},
        {"kind":"paragraph","text":"불확실한 미래를 한 숫자로 표현하면 정밀해 보이지만 오차를 숨깁니다. 범위와 조건을 쓰면 앵커에서 얼마나 조정했는지가 아니라 어떤 가정이 결과를 움직였는지 볼 수 있습니다."}
      ],
      "thought_experiment":{"title":"앵커링 재현실험의 세 조건","prompt":"학생들을 무작위로 낮은 숫자, 높은 숫자, 숫자 없음 조건에 배정한 뒤 같은 기업의 적정가치를 추정하게 합니다. 숫자가 무관하다는 경고도 절반에게만 준다면 무엇을 비교해야 앵커와 경고의 효과를 분리할 수 있을까요?","choices":["각 조건의 평균 추정치","추정치의 평균과 분산 및 상호작용","최종 가격을 맞힌 사람의 수만 비교"],"reflection":"무관한 숫자 대신 실제 52주 최고가를 쓰면 현실성은 높아지지만 무엇을 순수한 앵커 효과라고 부르기 어려워지는지 생각해보세요."},
      "practice":{"title":"설계와 해석의 쟁점","minutes":0,"steps":["무작위 숫자와 정보가 담긴 시장가격을 구분한다","사전지식이 앵커 효과를 조절할 가능성을 검토한다","평균 이동뿐 아니라 추정치 분산도 관찰해야 하는 이유를 생각한다","독립 추정과 시장가격 공개의 순서를 바꾼 실험을 설계한다"],"rule_template":"앵커의 인과효과를 보려면 숫자가 제공하는 정보와 단순 노출 효과를 분리한다."},
      "source_notes":[{"title":"Judgment under Uncertainty: Heuristics and Biases","authors":"Amos Tversky, Daniel Kahneman","year":1974,"url":"https://doi.org/10.1126/science.185.4157.1124","note":"대표성·가용성·앵커링과 조정 휴리스틱이 체계적 오류를 낳는 과정을 정리한다."},{"title":"Insensitivity to Future Consequences Following Damage to Human Prefrontal Cortex","authors":"Antoine Bechara et al.","year":1994,"url":"https://doi.org/10.1016/0010-0277(94)90018-3","note":"불확실한 선택에서 피드백과 미래 결과를 통합하는 과정의 신경심리학적 근거를 제공한다."}]
    },
    {
      "ordinal":5,
      "slug":"mental-accounting-money-fungibility",
      "title":"보너스 통장과 월급 통장의 돈은 정말 다른가",
      "subtitle":"돈에 붙인 이름이 소비와 위험 선택을 바꾸는 심리적 회계",
      "excerpt":"같은 10만원도 월급, 보너스, 투자수익이라는 이름에 따라 다르게 씁니다. 심리적 회계 모형이 이 차이를 어떻게 설명하는지 살펴봅니다.",
      "category":"소비자심리학",
      "tags":["심리적회계","보너스","예산","대체가능성"],
      "reading_minutes":7,
      "difficulty":"입문",
      "hero_kicker":"판단 연구 05 · 심리적 회계",
      "content_blocks":[
        {"kind":"paragraph","text":"월급에서 10만원을 쓰는 일은 망설이면서 카드 포인트나 투자수익 10만원은 쉽게 소비합니다. 화폐의 구매력은 같지만 마음속 장부는 돈의 출처에 서로 다른 사용 허가를 붙입니다."},
        {"kind":"heading","text":"이름표가 선택을 바꾼다"},
        {"kind":"paragraph","text":"심리적 회계는 돈과 결과를 별도 계정으로 분류하고 평가하는 방식입니다. 예산 관리에는 도움이 되지만, 전체 자산 관점에서는 동일한 돈을 다르게 취급하는 오류를 낳을 수 있습니다."},
        {"kind":"heading","text":"모형은 무엇을 설명하도록 설계되었나"},
        {"kind":"paragraph","text":"Thaler의 1985년 논문은 단일 실험 보고서라기보다 전망이론의 가치함수, 거래효용, 가계예산을 결합한 이론적 모형입니다. 핵심 비교는 같은 최종 부를 만드는 선택이라도 이득과 손실을 합산하거나 분리해 부호화하는 방식에 따라 매력이 달라진다는 것입니다. 이론의 설명력과 실제 개인에게 적용되는 규범적 처방은 구분해야 합니다."},
        {"kind":"paragraph","text":"‘수익금이니까 괜찮다’며 위험을 늘리거나, 저축이 있으면서 높은 카드빚을 유지하는 선택이 예입니다. 계정 간 벽이 이자율과 위험을 가릴 때 비용이 생깁니다."},
        {"kind":"callout","title":"출처를 지우는 질문","text":"이 10만원이 월급에서 왔다면 같은 사용을 하겠습니까? 반대로 필요한 지출이라면 보너스가 없어도 실행했겠습니까?"},
        {"kind":"heading","text":"좋은 이름표도 있다"},
        {"kind":"paragraph","text":"생활비·비상금·장기저축을 나누는 것은 자기통제에 유용할 수 있습니다. 문제는 이름표가 목적을 돕는지, 높은 이자와 과도한 위험을 못 보게 하는지입니다."},
        {"kind":"list","items":["모든 계정의 순자산과 금리를 한 화면에 적는다","보너스와 수익금에도 기본 배분 규칙을 적용한다","계정 이동을 막는 실제 비용이 있는지 확인한다","목적 없는 잔액은 전체 우선순위로 재배치한다"]},
        {"kind":"heading","text":"돈의 출처보다 돈의 임무"},
        {"kind":"paragraph","text":"합리적인 예산은 모든 돈을 한데 섞는 것이 아니라, 각 계정의 임무를 전체 목표와 연결하는 것입니다. 출처가 아니라 위험, 기한, 기회비용이 배분을 결정해야 합니다."}
      ],
      "thought_experiment":{"title":"최종 부가 같은 두 세계","prompt":"세계 A에서는 월급 20만원을 쓰고 환급금 20만원을 저축합니다. 세계 B에서는 월급을 저축하고 환급금을 씁니다. 세금·금리·유동성이 같고 최종 자산도 같다면 두 선택의 복지가 달라질 수 있을까요?","choices":["경제적으로 완전히 같다","심리적 만족까지 포함하면 다를 수 있다","돈의 출처가 달라 언제나 다르다"],"reflection":"대체가능성을 규범 기준으로 삼을 때와 자기통제 효용까지 복지에 포함할 때 답이 어떻게 달라지는지 논증해보세요."},
      "practice":{"title":"이론을 확장해볼 질문","minutes":0,"steps":["심리적 계정이 오류가 아니라 유용한 자기통제 장치인 조건을 찾는다","거래효용과 획득효용을 서로 다른 사례로 설명한다","저축과 고금리 부채를 동시에 보유하는 행동의 합리적 대안을 검토한다","이름표를 없앤 조건과 유지한 조건의 소비액을 비교하는 실험을 설계한다"],"rule_template":"화폐의 대체가능성과 심리적 계정이 제공하는 자기통제 편익을 함께 비교한다."},
      "source_notes":[{"title":"Mental Accounting and Consumer Choice","authors":"Richard H. Thaler","year":1985,"url":"https://doi.org/10.1287/mksc.4.3.199","note":"거래효용과 가계예산을 포함한 심리적 회계 모형을 제시한다."},{"title":"The Red and the Black: Mental Accounting of Savings and Debt","authors":"Drazen Prelec, George Loewenstein","year":1998,"url":"https://doi.org/10.1287/mksc.17.1.4","note":"저축과 부채를 동시에 보유하는 현상을 이중기입 심리회계로 설명한다."}]
    },
    {
      "ordinal":6,
      "slug":"pain-of-paying-digital-wallet",
      "title":"결제가 보이지 않을수록 소비의 브레이크도 흐려진다",
      "subtitle":"간편결제와 구독에서 ‘지불의 고통’을 다시 보이게 만드는 법",
      "excerpt":"결제와 소비가 시간적으로 분리되면 가격 신호가 약해집니다. 불편을 늘리지 않으면서 비용을 다시 인식하는 장치를 설계합니다.",
      "category":"소비자심리학",
      "tags":["지불의고통","간편결제","구독","결제분리"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 연구 06 · 결제의 고통",
      "content_blocks":[
        {"kind":"paragraph","text":"버튼 한 번으로 결제하고 다음 달에 카드대금을 합산해 보면, 구매 순간에는 가격이 거의 느껴지지 않습니다. 편리함은 시간을 줄이지만 비용과 소비의 연결도 약하게 만들 수 있습니다."},
        {"kind":"heading","text":"가격은 숫자이자 감각이다"},
        {"kind":"paragraph","text":"Prelec과 Loewenstein은 소비의 즐거움과 지불의 고통이 서로 연결되는 방식을 설명했습니다. 결제가 소비와 분리되면 즉각적인 고통은 줄지만, 자기통제를 돕는 가격 신호도 약해질 수 있습니다."},
        {"kind":"heading","text":"이론과 개인차 연구의 연결"},
        {"kind":"paragraph","text":"‘The Red and the Black’은 지불과 소비의 시간적 결합을 이중기입 심리회계로 설명한 이론 논문입니다. 이후 Rick·Cryder·Loewenstein은 지불의 고통이 큰 절약형과 작은 소비형을 구분하는 척도를 만들고, 가격 프레이밍을 달리한 구매 과제에서 집단 차이가 언제 커지는지 비교했습니다. 자기보고 척도와 실제 장기 소비의 차이는 해석의 한계입니다."},
        {"kind":"paragraph","text":"구독은 이 분리를 더 길게 만듭니다. 처음 결제 후 매달 자동 갱신되면 사용 여부를 다시 선택하지 않아도 비용이 나갑니다. 작은 금액의 반복은 총액을 보이지 않게 합니다."},
        {"kind":"callout","title":"편리함을 없애지 않고 신호만 복구하기","text":"결제 전 ‘월 금액’ 대신 ‘연간 총액’과 사용 1회당 비용을 표시하세요. 자동결제일 하루 전 알림을 두면 다시 선택할 기회가 생깁니다."},
        {"kind":"heading","text":"고통이 클수록 좋은 것은 아니다"},
        {"kind":"paragraph","text":"현금만 쓰거나 모든 결제를 어렵게 만들 필요는 없습니다. 필요한 소비까지 방해하는 과도한 마찰은 시간과 만족을 해칩니다. 목표는 고통을 키우는 것이 아니라 비용 정보를 적시에 보이게 하는 것입니다."},
        {"kind":"list","items":["구독료를 연간 총액으로 환산한다","최근 30일 실제 사용 횟수를 센다","결제일 전 재승인 알림을 둔다","충동구매에는 24시간 대기 규칙을 적용한다"]},
        {"kind":"heading","text":"보이지 않는 돈을 보이게"},
        {"kind":"paragraph","text":"좋은 결제 시스템은 편리하면서도 선택의 결과를 숨기지 않습니다. 총액, 빈도, 다음 결제일을 한 화면에 두면 소비의 즐거움과 예산의 현실을 함께 볼 수 있습니다."}
      ],
      "thought_experiment":{"title":"마찰이 다른 세 결제 인터페이스","prompt":"같은 상품을 현금, 비밀번호를 매번 입력하는 카드, 한 번 누르는 간편결제로 판매합니다. 가격은 같고 결제 절차만 다를 때 구매율과 구매 후 만족이 어떻게 달라질까요?","choices":["마찰이 적을수록 구매와 만족이 모두 증가한다","구매는 늘지만 만족은 반드시 늘지 않는다","결제수단은 아무 영향이 없다"],"reflection":"결제 마찰, 지출 가시성, 결제 시점의 분리를 각각 조작하려면 조건을 어떻게 나누어야 할지 설계해보세요."},
      "practice":{"title":"소비자 연구의 쟁점","minutes":0,"steps":["결제의 고통이 낮은 것과 거래비용이 낮은 것을 구분한다","자기보고 척도와 실제 구매행동이 불일치할 가능성을 검토한다","월 가격·연 가격·회당 가격 표시가 만드는 프레이밍을 비교한다","소비자 보호와 편리성 사이의 정책적 균형을 생각한다"],"rule_template":"결제수단의 편리성 효과와 가격 인식, 소비 후 만족을 별도의 결과변수로 측정한다."},
      "source_notes":[{"title":"The Red and the Black: Mental Accounting of Savings and Debt","authors":"Drazen Prelec, George Loewenstein","year":1998,"url":"https://doi.org/10.1287/mksc.17.1.4","note":"소비의 즐거움과 지불의 고통이 결제 시점과 결합 방식에 따라 달라지는 모형을 제시한다."},{"title":"Tightwads and Spendthrifts","authors":"Scott I. Rick, Cynthia E. Cryder, George Loewenstein","year":2008,"url":"https://doi.org/10.1086/523285","note":"지불의 고통 차이가 소비성향과 상황별 지출에 연결되는 양상을 분석한다."}]
    },
    {
      "ordinal":7,
      "slug":"myopic-loss-checking-frequency",
      "title":"계좌를 자주 볼수록 장기 계획이 짧아질 수 있다",
      "subtitle":"평가 빈도가 손실회피와 위험 선택을 증폭시키는 방식",
      "excerpt":"장기 투자도 자주 평가하면 단기 손실의 연속으로 경험될 수 있습니다. 평가 주기가 위험선택을 바꾸는 이론과 실험을 살펴봅니다.",
      "category":"행동금융학",
      "tags":["근시안적손실회피","평가빈도","장기투자","알림"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 연구 07 · 평가 빈도",
      "content_blocks":[
        {"kind":"paragraph","text":"10년 계획으로 시작한 투자도 알림을 매분 받으면 10년짜리 선택으로 느껴지지 않습니다. 화면을 열 때마다 짧은 구간의 손익이 새 결정처럼 다가옵니다."},
        {"kind":"heading","text":"시간 창이 위험의 모양을 바꾼다"},
        {"kind":"paragraph","text":"근시안적 손실회피는 손실에 민감한 사람이 결과를 자주 평가할 때 위험자산을 더 불편하게 느낄 수 있다는 설명입니다. 같은 장기 분포도 짧게 잘라 보면 손실 구간을 더 자주 마주칩니다."},
        {"kind":"heading","text":"평가 주기만 바꾼 실험"},
        {"kind":"paragraph","text":"Gneezy와 Potters는 같은 반복 도박을 제시하되 한 집단에는 매 회 결과와 재선택 기회를 주고, 다른 집단에는 여러 회의 결과를 묶어 보여주고 묶음 단위로 선택하게 했습니다. 보상 분포는 같지만 평가 빈도가 달랐고, 묶음 평가 집단이 위험 선택에 더 많이 배분했습니다. 이 설계는 평가 빈도의 인과효과를 분리하지만 실험실 도박을 장기 자산시장에 일반화할 때는 주의가 필요합니다."},
        {"kind":"paragraph","text":"확인 자체가 나쁜 것은 아닙니다. 레버리지, 마진콜, 만기가 있는 상품은 실시간 관리가 필요합니다. 하지만 장기 포트폴리오를 단기 알림으로 관리하면 투자 기한과 평가 기한이 충돌합니다."},
        {"kind":"callout","title":"확인과 행동을 분리하기","text":"화면은 볼 수 있지만 매매는 정해진 검토일에만 하도록 분리하세요. 예외는 손실한도, 현금수요, 가설 훼손 같은 사전 조건으로 한정합니다."},
        {"kind":"heading","text":"빈도를 낮출 수 없는 상품"},
        {"kind":"paragraph","text":"선물·옵션처럼 위험이 빠르게 변하는 상품은 확인 빈도보다 포지션 크기를 줄이는 것이 먼저입니다. 자주 봐야 안전한 규모라면, 감당 가능한 위험인지 다시 계산해야 합니다."},
        {"kind":"list","items":["투자 기한과 평가 기한을 각각 적는다","가격 알림과 행동 조건을 분리한다","정기 검토일을 달력에 고정한다","예외 행동 조건은 세 개 이하로 둔다"]},
        {"kind":"heading","text":"정보가 아니라 노출량을 관리한다"},
        {"kind":"paragraph","text":"더 자주 본다고 항상 더 많이 아는 것은 아닙니다. 같은 변동을 반복해 보는 것은 정보 추가가 아니라 감정 노출의 증가일 수 있습니다. 판단 빈도는 상품의 위험과 계획의 시간축에 맞춰야 합니다."}
      ],
      "thought_experiment":{"title":"같은 확률과정의 다른 편집본","prompt":"두 집단이 동일한 12개월 수익률 경로에 투자하지만 A는 매월 결과를 보고 다시 선택하고 B는 3개월 결과를 묶어서 본 뒤 선택합니다. 최종 정보량이 같아도 주식 배분이 달라진다면 원인은 무엇일까요?","choices":["손실을 관찰하는 횟수","정보의 총량","복리계산 능력만의 차이"],"reflection":"피드백 빈도와 실제로 결정을 바꿀 수 있는 빈도를 따로 조작하면 근시안적 손실회피의 어느 경로를 식별할 수 있을지 생각해보세요."},
      "practice":{"title":"실험 결과를 확장하는 질문","minutes":0,"steps":["평가 빈도와 거래 기회의 빈도를 별도 변수로 구분한다","단기 손실회피와 합리적 정보반응을 식별할 기준을 세운다","수익률 자기상관이 있을 때 해석이 어떻게 달라지는지 검토한다","실험실의 반복 도박을 장기투자에 일반화할 때의 한계를 찾는다"],"rule_template":"같은 정보라도 묶음의 크기와 선택 가능 시점이 위험선호를 다르게 보이게 할 수 있다."},
      "source_notes":[{"title":"Myopic Loss Aversion and the Equity Premium Puzzle","authors":"Shlomo Benartzi, Richard H. Thaler","year":1995,"url":"https://doi.org/10.2307/2118511","note":"손실회피와 잦은 평가의 결합이 장기 위험 선택에 미치는 효과를 모형화한다."},{"title":"An Experiment on Risk Taking and Evaluation Periods","authors":"Uri Gneezy, Jan Potters","year":1997,"url":"https://doi.org/10.1162/003355397555217","note":"평가 기간이 위험 투자 선택에 영향을 주는지 실험으로 검토한다."}]
    },
    {
      "ordinal":8,
      "slug":"house-money-risk-budget",
      "title":"수익금도 내 돈이다: ‘공짜 돈’이 위험 한도를 무너뜨릴 때",
      "subtitle":"직전 이익과 현재 베팅을 한 장부에서 분리하는 위험예산",
      "excerpt":"수익 직후에는 잃어도 본전이라는 느낌이 위험을 키웁니다. 직전 결과와 다음 선택을 분리해 일정한 위험예산을 유지합니다.",
      "category":"행동재무학",
      "tags":["하우스머니효과","위험예산","직전수익","포지션크기"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 연구 08 · 하우스머니 효과",
      "content_blocks":[
        {"kind":"paragraph","text":"큰 수익을 낸 다음 거래에서 평소보다 계약 수를 늘리는 일이 있습니다. ‘어차피 번 돈 일부’라는 표현은 수익금을 내 자산이 아닌 카지노의 돈처럼 느끼게 합니다."},
        {"kind":"heading","text":"직전 결과가 다음 위험의 가격을 바꾼다"},
        {"kind":"paragraph","text":"하우스머니 효과는 앞선 이익 뒤에 위험감수가 커지는 현상을 가리킵니다. 반대로 손실 뒤에는 본전 기회를 특별히 매력적으로 보는 손익분기 효과가 나타날 수 있습니다."},
        {"kind":"heading","text":"선행 결과를 조작한 순차 선택 실험"},
        {"kind":"paragraph","text":"Thaler와 Johnson은 참가자에게 먼저 이익 또는 손실을 경험하게 한 다음 새로운 실돈 위험선택을 제시했습니다. 연구 질문은 최종 부가 아니라 직전 결과의 부호와 통합 가능성이 다음 도박의 매력을 바꾸는가였습니다. 순차적 프레이밍을 통제한 장점이 있지만, ‘하우스머니’가 모든 표본과 시장에서 안정적으로 같은 크기로 나타난다고 단정해서는 안 됩니다."},
        {"kind":"paragraph","text":"규범적으로 다음 선택은 증가분의 결과만 평가해야 합니다. 직전 수익은 감당 능력을 실제로 높일 수 있지만, 그만큼 위험한 선택이 자동으로 좋아지는 것은 아닙니다."},
        {"kind":"callout","title":"수익을 먼저 자산으로 편입하기","text":"거래가 끝나는 순간 수익을 총자산에 합산하고 다음 거래의 위험 한도를 동일한 비율 규칙으로 다시 계산하세요. ‘공짜 돈’ 항목을 만들지 않습니다."},
        {"kind":"heading","text":"위험을 늘릴 수 있는 합리적 이유"},
        {"kind":"paragraph","text":"총자산 증가로 절대 위험예산이 커지거나, 전략의 검증된 우위가 개선되었다면 규모를 조정할 수 있습니다. 단지 기분이 가벼워졌다는 이유와 구분하려면 사전 공식이 필요합니다."},
        {"kind":"list","items":["직전 손익을 총자산에 즉시 합산한다","거래당 최대 손실 비율을 고정한다","연속 수익 뒤 규모 상한을 둔다","본전이라는 표현을 계획서에서 제거한다"]},
        {"kind":"heading","text":"결과가 아니라 규칙이 규모를 정한다"},
        {"kind":"paragraph","text":"연승은 전략의 증거일 수도 우연일 수도 있습니다. 표본이 충분하지 않은 상태에서 규모를 키우면 운을 실력으로 오인합니다. 다음 위험은 직전 감정이 아니라 장기 위험예산이 결정해야 합니다."}
      ],
      "thought_experiment":{"title":"경로는 다르지만 현재 부는 같은 두 사람","prompt":"두 사람의 현재 자산은 1,100만원으로 같습니다. A는 오늘 100만원을 벌었고 B는 어제 200만원을 잃은 뒤 오늘 100만원을 회복했습니다. 동일한 다음 도박을 평가할 때 두 사람의 선택이 달라질 이유가 있을까요?","choices":["최종 부가 같으므로 같아야 한다","최근 이익의 편집 방식 때문에 달라질 수 있다","B만 본전회복 동기가 있으므로 언제나 더 위험해진다"],"reflection":"최종 부, 직전 결과, 기준점을 각각 독립적으로 조작하면 하우스머니 효과와 손익분기 효과를 어떻게 구분할 수 있을지 생각해보세요."},
      "practice":{"title":"순차 선택을 해석할 쟁점","minutes":0,"steps":["최종 부 이론과 결과의 심리적 편집이 내놓는 예측을 비교한다","실험 보상액의 크기가 실제 자산 대비 얼마나 중요한지 검토한다","이익 후 위험증가와 전략 학습을 구분할 통제조건을 만든다","투자에서 직전 수익이 위험감당 능력을 실제로 바꾸는 경우를 찾는다"],"rule_template":"직전 결과의 이름표, 현재 총자산, 다음 선택의 기대가치를 서로 분리한다."},
      "source_notes":[{"title":"Gambling with the House Money and Trying to Break Even","authors":"Richard H. Thaler, Eric J. Johnson","year":1990,"url":"https://doi.org/10.1287/mnsc.36.6.643","note":"앞선 이익과 손실이 이후 위험 선택에 미치는 하우스머니·손익분기 효과를 실험한다."},{"title":"Mental Accounting and Consumer Choice","authors":"Richard H. Thaler","year":1985,"url":"https://doi.org/10.1287/mksc.4.3.199","note":"결과를 별도 계정으로 부호화하는 심리적 회계의 기초를 제시한다."}]
    },
    {
      "ordinal":9,
      "slug":"choice-overload-investment-products",
      "title":"선택지가 많아질수록 비교표는 짧아져야 한다",
      "subtitle":"ETF·보험·쇼핑 옵션의 선택 과부하를 기준 세 개로 줄이는 법",
      "excerpt":"상품이 많으면 더 좋은 선택이 가능해 보이지만 결정 피로와 후회를 키울 수 있습니다. 먼저 기준을 정해 선택 집합을 줄입니다.",
      "category":"소비자심리학",
      "tags":["선택과부하","결정피로","ETF","비교기준"],
      "reading_minutes":6,
      "difficulty":"입문",
      "hero_kicker":"판단 연구 09 · 선택 과부하",
      "content_blocks":[
        {"kind":"paragraph","text":"검색창에 ‘미국 주식 ETF’를 입력하면 비슷해 보이는 상품이 끝없이 나옵니다. 선택지가 많으면 최적을 찾을 가능성이 커지는 동시에 비교 비용과 놓친 대안에 대한 후회도 커집니다."},
        {"kind":"heading","text":"더 많은 선택이 항상 더 나은가"},
        {"kind":"paragraph","text":"Iyengar와 Lepper의 연구는 많은 선택지가 관심을 끌 수 있지만 실제 선택과 만족을 낮출 가능성을 보여줬습니다. 다만 선택 과부하는 상황과 전문성에 따라 달라지므로 ‘항상 적을수록 좋다’는 법칙은 아닙니다."},
        {"kind":"heading","text":"잼 진열대 현장실험의 구조"},
        {"kind":"paragraph","text":"유명한 현장연구는 식료품점 시식대를 24종 잼 조건과 6종 잼 조건으로 번갈아 운영해 멈춰 선 비율과 실제 구매율을 비교했습니다. 많은 선택은 더 많은 관심을 끌었지만 적은 선택 조건에서 구매 전환이 높았습니다. 이후 메타분석은 효과 크기가 선택 난이도, 선호의 명확성, 과제 맥락에 따라 달라진다고 지적하므로 하나의 잼 실험을 보편 법칙으로 읽어서는 안 됩니다."},
        {"kind":"paragraph","text":"핵심은 상품 수가 아니라 비교 구조입니다. 목표가 불명확한 상태에서 수십 개 속성을 동시에 최적화하려 하면 눈에 띄는 브랜드나 최근 수익률로 도피하기 쉽습니다."},
        {"kind":"callout","title":"상품보다 탈락 기준을 먼저","text":"반드시 필요한 기준 세 개와 즉시 탈락 기준 두 개를 먼저 정하세요. 기준을 통과한 후보만 세 개 이하로 남깁니다."},
        {"kind":"heading","text":"충분히 좋은 선택의 가치"},
        {"kind":"paragraph","text":"비용이 낮고 목적에 맞으며 이해 가능한 상품이라면, 미세한 차이를 찾는 시간보다 실행과 유지가 더 중요할 수 있습니다. 완벽한 선택을 찾느라 결정을 미루는 것도 비용입니다."},
        {"kind":"list","items":["목표와 보유기간을 먼저 쓴다","필수 기준 세 개를 정한다","탈락 기준 두 개로 후보를 줄인다","최종 후보는 같은 단위로 비교한다"]},
        {"kind":"heading","text":"선택 후에는 재검색을 멈춘다"},
        {"kind":"paragraph","text":"선택 직후 계속 검색하면 선택하지 않은 장점만 보이고 현재 선택의 단점이 커 보입니다. 재검토 날짜와 조건을 정해두면 불필요한 비교를 줄이고 중요한 변화에만 반응할 수 있습니다."}
      ],
      "thought_experiment":{"title":"선택지 수 × 선호 명확성의 2×2 실험","prompt":"참가자에게 ETF 6개 또는 30개를 보여주고, 절반에게는 투자목표와 비교기준을 미리 정하게 합니다. 선택률과 만족도가 가장 낮을 조건은 어디일까요?","choices":["30개·기준 없음","30개·기준 있음","6개·기준 없음"],"reflection":"후보 수의 주효과뿐 아니라 선호 명확성과의 상호작용을 측정하면 ‘많아서 문제’라는 설명이 어떻게 정교해지는지 생각해보세요."},
      "practice":{"title":"선택 과부하 논쟁의 쟁점","minutes":0,"steps":["시식대에 멈추는 행동과 실제 구매를 다른 종속변수로 본다","선택지 수와 선택지 간 유사성을 구분한다","메타분석의 평균 효과가 작을 때 조절변수의 의미를 검토한다","전문성이 많은 선택의 비용을 낮추는 실험조건을 설계한다"],"rule_template":"선택지의 개수만이 아니라 과제 난이도, 선호 명확성, 비교비용의 상호작용을 본다."},
      "source_notes":[{"title":"When Choice Is Demotivating: Can One Desire Too Much of a Good Thing?","authors":"Sheena S. Iyengar, Mark R. Lepper","year":2000,"url":"https://doi.org/10.1037/0022-3514.79.6.995","note":"선택지 수가 동기와 실제 선택, 만족에 미치는 영향을 세 실험으로 검토한다."},{"title":"Choice Overload: A Conceptual Review and Meta-Analysis","authors":"Benjamin Scheibehenne, Rainer Greifeneder, Peter M. Todd","year":2010,"url":"https://doi.org/10.1086/651235","note":"선택 과부하 효과가 맥락에 따라 달라짐을 메타분석으로 정리한다."}]
    },
    {
      "ordinal":10,
      "slug":"attention-stock-selection",
      "title":"눈에 띈 종목은 좋은 종목이 아니라 검색을 통과한 종목일 뿐이다",
      "subtitle":"급등주·뉴스 종목이 매수 후보가 되는 주의 편향의 구조",
      "excerpt":"뉴스와 급등률은 수천 종목 중 일부만 보이게 합니다. 관심을 끈 이유와 투자 근거를 분리해 후보군을 다시 만듭니다.",
      "category":"행동금융학",
      "tags":["주의편향","급등주","뉴스","후보선정"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 연구 10 · 주의 편향",
      "content_blocks":[
        {"kind":"paragraph","text":"오늘 가장 많이 오른 종목과 속보에 등장한 기업은 쉽게 매수 후보가 됩니다. 그러나 눈에 띈 것은 기대수익이 높다는 증거가 아니라, 우리의 제한된 주의 관문을 통과했다는 사실입니다."},
        {"kind":"heading","text":"선호 이전에 후보군이 결정된다"},
        {"kind":"paragraph","text":"개인투자자는 살 수 있는 종목이 너무 많아 모두 분석하기 어렵습니다. Barber와 Odean은 뉴스, 비정상적 거래량, 극단적 수익률로 주의를 끈 종목에 개인의 순매수가 몰리는 경향을 분석했습니다."},
        {"kind":"heading","text":"주의를 직접 측정하지 않고 대리변수를 쓴 설계"},
        {"kind":"paragraph","text":"연구진은 개인·기관의 거래자료를 뉴스 보도, 비정상 거래량, 극단적 일간수익률과 결합했습니다. 이 세 지표를 ‘주의를 끈 정도’의 대리변수로 삼아 매수 불균형을 비교한 관찰연구입니다. 대리변수는 직접적인 시선 측정이 아니므로 뉴스의 정보효과, 가격추종 전략, 유동성 같은 교란요인을 함께 고려해야 합니다."},
        {"kind":"paragraph","text":"매도는 이미 보유한 좁은 목록에서 고르지만 매수는 수천 종목 중 골라야 합니다. 그래서 관심이 먼저 후보군을 만들고, 분석은 그 뒤에 이루어집니다. 분석이 정교해도 후보군이 편향되면 결론도 제한됩니다."},
        {"kind":"callout","title":"발견 이유와 보유 이유를 분리하기","text":"‘뉴스에서 봤다’는 발견 경로입니다. 매수 이유에는 가격, 현금흐름, 위험, 반증 조건처럼 발견 경로와 독립된 근거만 적으세요."},
        {"kind":"heading","text":"뉴스가 실제 정보일 때"},
        {"kind":"paragraph","text":"주의를 끈 사건이 가치에 중요한 새 정보일 수 있습니다. 문제는 뉴스가 아니라 비교군 부재입니다. 같은 조건의 조용한 기업과 비교해야 정보의 가치와 관심 프리미엄을 구분할 수 있습니다."},
        {"kind":"list","items":["발견 경로를 한 줄로 적는다","동종 비교군 두 개를 강제로 추가한다","뉴스가 현금흐름을 바꾸는 경로를 적는다","하루 뒤에도 근거가 유지되는지 재검토한다"]},
        {"kind":"heading","text":"보이는 것 밖에서 후보를 만든다"},
        {"kind":"paragraph","text":"체계적 스크리닝은 완벽하지 않지만 주의가 만든 후보군을 넓힙니다. 최근 급등률을 기준에서 빼고 목적에 맞는 재무·위험 조건으로 먼저 걸러내면, 관심과 가치의 순서를 뒤집을 수 있습니다."}
      ],
      "thought_experiment":{"title":"무작위 뉴스 노출 실험","prompt":"가치와 무관한 중립 뉴스가 붙은 종목을 참가자마다 무작위로 다르게 보여주고 가상 포트폴리오를 구성하게 합니다. 노출 종목의 편입률이 높다면 주의의 인과효과라고 볼 수 있을까요?","choices":["무작위화했으므로 강한 근거다","뉴스 문구가 선호를 바꾸는 정보효과를 추가로 통제해야 한다","가상투자이므로 아무 의미가 없다"],"reflection":"시선추적 자료와 실제 금전 보상을 더하면 ‘보았다→검토했다→매수했다’라는 매개경로를 어떻게 시험할 수 있을지 설계해보세요."},
      "practice":{"title":"관찰자료와 인과추론의 쟁점","minutes":0,"steps":["뉴스·거래량·극단수익률이 주의의 대리변수로서 갖는 한계를 찾는다","정보효과와 단순 노출 효과를 구분할 통제집단을 설계한다","매수 후보군과 최종 선호를 서로 다른 단계로 모형화한다","기관과 개인의 매수 제약 차이가 결과에 미치는 영향을 검토한다"],"rule_template":"눈에 띈 이유, 실제 정보, 비교 후 선호를 서로 다른 단계로 측정한다."},
      "source_notes":[{"title":"All That Glitters: The Effect of Attention and News on the Buying Behavior of Individual and Institutional Investors","authors":"Brad M. Barber, Terrance Odean","year":2008,"url":"https://doi.org/10.1093/rfs/hhm079","note":"뉴스·거래량·극단 수익률로 주의를 끈 종목에 개인투자자의 매수가 집중되는지 분석한다."},{"title":"Judgment under Uncertainty: Heuristics and Biases","authors":"Amos Tversky, Daniel Kahneman","year":1974,"url":"https://doi.org/10.1126/science.185.4157.1124","note":"가용성이 확률과 빈도 판단을 왜곡할 수 있음을 설명한다."}]
    },
    {
      "ordinal":11,
      "slug":"present-bias-subscription-renewal",
      "title":"오늘의 편리함이 내일의 자동결제를 이기는 이유",
      "subtitle":"현재 편향을 의지 대신 사전 약속으로 다루는 소비 설계",
      "excerpt":"지금의 작은 편익은 크게 느껴지고 미래 비용은 희미해집니다. 구독·할부·저축 결정을 미래의 나에게 떠넘기지 않는 약속 장치입니다.",
      "category":"행동경제학",
      "tags":["현재편향","자동결제","자기통제","약속장치"],
      "reading_minutes":7,
      "difficulty":"중급",
      "hero_kicker":"판단 연구 11 · 현재 편향",
      "content_blocks":[
        {"kind":"paragraph","text":"무료 체험을 시작할 때는 다음 달 전에 해지할 계획입니다. 그러나 해지는 미래의 작은 수고가 되고, 오늘은 즉시 얻는 편리함이 큽니다. 시간이 지나면 같은 사람이 다른 선택을 합니다."},
        {"kind":"heading","text":"미래의 나는 오늘의 나와 협상한다"},
        {"kind":"paragraph","text":"현재 편향은 가까운 보상과 비용에 불균형하게 큰 가중치를 두는 경향입니다. Laibson의 모형은 시간에 따라 선호가 달라질 때 사람들이 미래 선택을 제한하는 약속 장치를 원할 수 있음을 보여줍니다."},
        {"kind":"heading","text":"실험 결과가 아니라 동학을 비교한 모형"},
        {"kind":"paragraph","text":"Laibson은 즉시 보상에 추가 가중치를 두는 준쌍곡 할인 구조와, 현금화에 시간이 걸리는 비유동 자산을 약속 장치로 결합했습니다. O'Donoghue와 Rabin은 미래 자기통제 문제를 아는 사람과 모르는 사람, 즉각 비용 과제와 즉각 보상 과제를 구분해 미루기 예측을 도출했습니다. 이는 인과 실험이 아니라 가정에서 행동 예측을 논리적으로 도출하는 이론 설계입니다."},
        {"kind":"paragraph","text":"문제는 미래의 내가 더 성실할 것이라는 낙관입니다. 해지, 저축, 기록처럼 즉시 비용이 드는 행동은 미루고, 쇼핑·게임·레버리지처럼 즉시 보상이 있는 행동은 앞당기기 쉽습니다."},
        {"kind":"callout","title":"미래 계획을 오늘 실행으로 바꾸기","text":"무료 체험을 시작하는 순간 해지 검토 일정을 등록하고, 저축은 월말 잔액이 아니라 급여일 자동이체로 설정하세요."},
        {"kind":"heading","text":"약속 장치의 비용"},
        {"kind":"paragraph","text":"모든 유동성을 잠그면 예상치 못한 상황에 대응하기 어렵습니다. 좋은 약속 장치는 취소 가능성과 마찰의 강도를 목적에 맞춥니다. 비상자금은 유동적으로, 충동 예산은 제한적으로 설계할 수 있습니다."},
        {"kind":"list","items":["미래 행동의 날짜와 시간을 지금 정한다","즉시 보상 앞에 짧은 대기시간을 둔다","저축은 소득 직후 자동화한다","약속을 깰 수 있는 합리적 예외를 적는다"]},
        {"kind":"heading","text":"의지보다 환경이 오래간다"},
        {"kind":"paragraph","text":"자기통제 실패를 성격 문제로만 보면 매번 같은 싸움을 반복합니다. 선택 환경을 바꾸면 미래의 내가 결정을 다시 시작할 필요가 줄어듭니다. 좋은 계획은 미래의 나를 믿는 대신 돕습니다."}
      ],
      "thought_experiment":{"title":"달력만 이동한 두 선택","prompt":"오늘 10만원과 1년 뒤 12만원 중에서는 오늘을 고르지만, 1년 뒤 10만원과 2년 뒤 12만원 중에서는 후자를 고른다고 합시다. 두 선택의 간격과 보상비율이 같은데 선호가 뒤집힌 이유를 어떤 모형이 설명할까요?","choices":["일정한 지수할인","현재에 추가 가중치를 주는 준쌍곡 할인","위험중립 기대효용만으로 충분하다"],"reflection":"실제 보상의 지급확률과 미래 지급에 대한 불신도 선호역전을 만들 수 있습니다. 현재 편향과 신뢰 문제를 분리할 실험 장치를 생각해보세요."},
      "practice":{"title":"시간선호 모형의 쟁점","minutes":0,"steps":["지수할인과 준쌍곡 할인이 예측하는 동태적 일관성을 비교한다","현재 편향과 미래 보상의 불확실성을 식별하는 설계를 구상한다","자신의 편향을 아는 사람과 모르는 사람의 약속장치 수요를 비교한다","유동성 제한이 자기통제 편익과 비상대응 비용을 함께 만드는 이유를 검토한다"],"rule_template":"보상의 시간거리, 지급 신뢰도, 즉시성에 대한 추가 가중치를 별도로 추정한다."},
      "source_notes":[{"title":"Golden Eggs and Hyperbolic Discounting","authors":"David Laibson","year":1997,"url":"https://doi.org/10.1162/003355397555253","note":"시간 비일관적 선호와 자기통제를 위한 약속 장치의 역할을 경제모형으로 분석한다."},{"title":"Doing It Now or Later","authors":"Ted O'Donoghue, Matthew Rabin","year":1999,"url":"https://doi.org/10.1257/aer.89.1.103","note":"현재 편향과 자기통제 인식이 미루기 및 즉시 보상 행동에 미치는 효과를 분석한다."}]
    }
  ]
  $articles$::jsonb) as x(
    ordinal integer,
    slug text,
    title text,
    subtitle text,
    excerpt text,
    category text,
    tags jsonb,
    reading_minutes integer,
    difficulty text,
    hero_kicker text,
    content_blocks jsonb,
    thought_experiment jsonb,
    practice jsonb,
    source_notes jsonb
  )
)
insert into public.articles (
  slug, version, is_current, status, title, subtitle, excerpt, category, tags,
  reading_minutes, difficulty, hero_kicker, content_blocks, thought_experiment,
  practice, source_notes, author_agent, published_at
)
select
  slug, 1, true, 'PUBLISHED', title, subtitle, excerpt, category,
  array(select jsonb_array_elements_text(tags)), reading_minutes, difficulty,
  hero_kicker, content_blocks, thought_experiment, practice, source_notes,
  'codex:manual-research-batch-01', now() - ((11 - ordinal) * interval '1 minute')
from batch
on conflict (slug, version) do update
set is_current = true,
    status = 'PUBLISHED',
    title = excluded.title,
    subtitle = excluded.subtitle,
    excerpt = excluded.excerpt,
    category = excluded.category,
    tags = excluded.tags,
    reading_minutes = excluded.reading_minutes,
    difficulty = excluded.difficulty,
    hero_kicker = excluded.hero_kicker,
    content_blocks = excluded.content_blocks,
    thought_experiment = excluded.thought_experiment,
    practice = excluded.practice,
    source_notes = excluded.source_notes,
    author_agent = excluded.author_agent,
    published_at = excluded.published_at;

commit;
